# Dependabot Configuration for OvenAI Project
# This file configures how Dependabot manages dependency updates

version: 2
updates:
  # Temporarily disable npm dependency updates to prevent excessive PRs
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    # Disable automatic PRs completely
    open-pull-requests-limit: 1
    # Add ignore patterns to prevent any updates
    ignore:
      # Ignore ALL dependencies temporarily to stop PR flood
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]
    # Custom commit message
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    # Add labels to PRs (for when we re-enable)
    labels:
      - "dependencies"
      - "automated"
      - "low-priority"
    # Add reviewers (optional - add your GitHub username)
    reviewers:
      - "broddo-baggins"  # Replace with your actual GitHub username
    # Add assignees (optional)
    assignees:
      - "broddo-baggins"  # Replace with your actual GitHub username

  # Also disable GitHub Actions updates temporarily
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "10:00"
      timezone: "America/New_York"
    # Disable automatic PRs completely
    open-pull-requests-limit: 0
    # Ignore all GitHub Actions updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "ci-cd"
      - "low-priority"
    reviewers:
      - "broddo-baggins"  # Replace with your actual GitHub username

  # Disable Docker updates temporarily
  # - package-ecosystem: "docker"
  #   directory: "/"
  #   schedule:
  #     interval: "monthly"
  #   open-pull-requests-limit: 2
  #   commit-message:
  #     prefix: "docker"
  #   labels:
  #     - "docker"
  #     - "infrastructure" 