name: '📊 Monitoring & Health Checks'

# Add permissions to allow artifact management
permissions:
  actions: write
  contents: read

on:
  workflow_run:
    workflows: ["Basic CI - Build & Unit Tests", "Integration Tests", "Accessibility Tests", "E2E Tests"]
    types: [completed]
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:
  push:
    branches: [main]

env:
  NODE_VERSION: '20.9.0'

jobs:
  monitor-workflows:
    name: 'Monitor Workflow Health'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Check Workflow Status'
        id: workflow-status
        run: |
          echo "workflow_name=${{ github.event.workflow_run.name }}" >> $GITHUB_OUTPUT
          echo "workflow_status=${{ github.event.workflow_run.conclusion }}" >> $GITHUB_OUTPUT
          echo "branch=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_OUTPUT
          echo "commit=${{ github.event.workflow_run.head_sha }}" >> $GITHUB_OUTPUT

      - name: 'Create Failure Report'
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: |
          echo "# Workflow Failure Report" > failure-report.md
          echo "**Workflow:** ${{ steps.workflow-status.outputs.workflow_name }}" >> failure-report.md
          echo "**Status:** FAILED" >> failure-report.md
          echo "**Branch:** ${{ steps.workflow-status.outputs.branch }}" >> failure-report.md
          echo "**Commit:** ${{ steps.workflow-status.outputs.commit }}" >> failure-report.md
          echo "**Time:** $(date)" >> failure-report.md
          echo "" >> failure-report.md
          echo "## Immediate Actions Required" >> failure-report.md
          echo "1. Review workflow logs" >> failure-report.md
          echo "2. Check for resource conflicts" >> failure-report.md
          echo "3. Verify environment variables" >> failure-report.md
          echo "4. Test in local environment" >> failure-report.md

      - name: 'Create Success Report'
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: |
          echo "# Workflow Success Report" > success-report.md
          echo "**Workflow:** ${{ steps.workflow-status.outputs.workflow_name }}" >> success-report.md
          echo "**Status:** PASSED" >> success-report.md
          echo "**Branch:** ${{ steps.workflow-status.outputs.branch }}" >> success-report.md
          echo "**Commit:** ${{ steps.workflow-status.outputs.commit }}" >> success-report.md
          echo "**Time:** $(date)" >> success-report.md

      - name: 'Upload Reports'
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: workflow-monitoring-report-${{ github.run_number }}
          path: "*.md"
          retention-days: 30

  cleanup-resources:
    name: 'Resource Management'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: always()
    permissions:
      actions: write
      contents: read
    
    steps:
      - name: 'Clean Up Old Artifacts'
        uses: actions/github-script@v6
        with:
          script: |
            const artifacts = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            
            const oldArtifacts = artifacts.data.artifacts.filter(artifact => {
              const createdAt = new Date(artifact.created_at);
              const weekAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
              return createdAt < weekAgo;
            });
            
            for (const artifact of oldArtifacts) {
              try {
                await github.rest.actions.deleteArtifact({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  artifact_id: artifact.id,
                });
                console.log(`Deleted artifact: ${artifact.name}`);
              } catch (error) {
                console.log(`Failed to delete artifact ${artifact.name}: ${error.message}`);
              }
            }

      - name: 'Generate Resource Report'
        run: |
          echo "# Resource Management Report" > resource-report.md
          echo "**Date:** $(date)" >> resource-report.md
          echo "" >> resource-report.md
          echo "## Actions Taken" >> resource-report.md
          echo "- Cleaned up artifacts older than 7 days" >> resource-report.md
          echo "- Generated monitoring reports" >> resource-report.md
          echo "- Verified workflow health" >> resource-report.md

  notify-status:
    name: 'Log Workflow Status'
    runs-on: ubuntu-latest
    needs: [monitor-workflows]
    if: always()
    
    steps:
      - name: 'Log Failure Status'
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: |
          echo "🚨 WORKFLOW FAILURE DETECTED 🚨"
          echo "================================"
          echo "Workflow: ${{ github.event.workflow_run.name }}"
          echo "Branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Status: FAILED"
          echo "Commit: ${{ github.event.workflow_run.head_sha }}"
          echo "Time: ${{ github.event.workflow_run.created_at }}"
          echo ""
          echo "Action Required:"
          echo "1. Check workflow logs: ${{ github.event.workflow_run.html_url }}"
          echo "2. Review recent changes"
          echo "3. Fix failing tests/builds"
          echo "4. Re-run workflow"
          echo ""
          echo "Repository: ${{ github.repository }}"
          echo "Run ID: ${{ github.event.workflow_run.id }}"
          echo "================================"

      - name: 'Log Success Status'
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: |
          echo "✅ Workflow completed successfully"
          echo "Workflow: ${{ github.event.workflow_run.name }}"
          echo "Branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Status: SUCCESS"

  # TEMPORARILY DISABLED DUE TO BILLING ISSUES  
  health-check:
    name: '🏥 Health Check'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: false  # DISABLED - Remove this line when billing is resolved
    
    steps:
      - name: 'Check Repository Health'
        run: |
          echo "# System Health Report" > health-report.md
          echo "**Timestamp:** $(date)" >> health-report.md
          echo "" >> health-report.md
          echo "## Workflow Status" >> health-report.md
          echo "- Basic CI: Monitoring" >> health-report.md
          echo "- Integration Tests: Monitoring" >> health-report.md
          echo "- Accessibility Tests: Monitoring" >> health-report.md
          echo "- E2E Tests: Monitoring" >> health-report.md
          echo "" >> health-report.md
          echo "## Resource Status" >> health-report.md
          echo "- Artifacts: Managed" >> health-report.md
          echo "- Cleanup: Active" >> health-report.md
          echo "- Monitoring: Active" >> health-report.md

      - name: 'Upload Health Report'
        uses: actions/upload-artifact@v4
        with:
          name: system-health-report
          path: health-report.md
          retention-days: 7