project_id = "smfjpyxekyyqmsobqszh"

[functions.create-admin-user]
verify_jwt = false

# [functions.syncAirtableLeads] (Removed as Airtable is no longer used)
# verify_jwt = false

[functions.create-specific-users]
verify_jwt = false

[functions.password-reset]
verify_jwt = false

[functions.delete-user-account]
verify_jwt = false

